language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
branches:
  only:
    - master
    - /^feature\/.*/
    - /-stable$/
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.1.0
      jdk: openjdk6
    - rvm: 2.1.0
      jdk: oraclejdk7
  allow_failures:
    - rvm: jruby-19mode
before_install:
  - wget https://foundationdb.com/downloads/I_accept_the_FoundationDB_Community_License_Agreement/1.0.1/foundationdb-clients_1.0.1-1_amd64.deb
  - wget https://foundationdb.com/downloads/I_accept_the_FoundationDB_Community_License_Agreement/1.0.1/foundationdb-server_1.0.1-1_amd64.deb
  - sudo dpkg -i foundationdb-clients_1.0.1-1_amd64.deb
  - sudo dpkg -i foundationdb-server_1.0.1-1_amd64.deb
