language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-19mode
  - jruby-head
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: oraclejdk8
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: oraclejdk8
    - rvm: 2.1.0
      jdk: openjdk6
    - rvm: 2.1.0
      jdk: oraclejdk7
    - rvm: 2.1.0
      jdk: oraclejdk8
    - rvm: ruby-head
      jdk: openjdk6
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: oraclejdk8
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - jdk: oraclejdk8
before_install:
  - wget https://foundationdb.com/downloads/I_accept_the_FoundationDB_Community_License_Agreement/1.0.1/foundationdb-clients_1.0.1-1_amd64.deb
  - wget https://foundationdb.com/downloads/I_accept_the_FoundationDB_Community_License_Agreement/1.0.1/foundationdb-server_1.0.1-1_amd64.deb
  - sudo dpkg -i foundationdb-clients_1.0.1-1_amd64.deb
  - sudo dpkg -i foundationdb-server_1.0.1-1_amd64.deb
addons:
  code_climate:
    repo_token: 8bd71907fa5f14a405d4adade4ddd62dc4c7d5a2470e025f5c6899fc32ac2898
