require 'rubygems'
require 'rubygems/command.rb'
require 'rubygems/dependency_installer.rb'

task :default => [:msgpack]

task :msgpack do
  begin
    Gem::Command.build_args = ARGV
  rescue NoMethodError
  end
  inst = Gem::DependencyInstaller.new
  begin
    if RUBY_PLATFORM == 'java'
      inst.install 'msgpack-jruby', '~> 1.3.2'
    else
      inst.install 'msgpack', '~> 0.5.8'
    end
  rescue
    exit(1)
  end
end
